# Loading a Sample Dataset and Calculating the Mean using NumPy

In [1]:
# import package
import numpy as np

In [2]:
# load the data
dataset = np.genfromtxt('Datasets/normal_distribution.csv', delimiter=',')
dataset

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465,
         98.80084371, 105.95297652,  98.37481387, 106.54654286],
       [ 91.37294597, 100.96781394, 100.40118279, 113.42090475,
        105.48508838,  91.6604946 , 106.1472841 ,  95.08715803],
       [101.20862522, 103.5730309 , 100.28690912, 105.85269352,
         93.37126331, 108.57980357, 100.79478953,  94.20019732],
       [102.80387079,  98.29687616,  93.24376389,  97.24130034,
         89.03452725,  96.2832753 , 104.60344836, 101.13442416],
       [106.71751618, 102.97585605,  98.45723272, 100.72418901,
        106.39798503,  95.46493436,  94.35373179, 106.83273763],
       [ 96.02548256, 102.82360856, 106.47551845, 101.34745901,
        102.45651798,  98.7476749

In [3]:
# print the shape
dataset.shape

(24, 8)

In [4]:
# calculate the mean of the first row
np.mean(dataset[0])

100.177647525

In [5]:
# calculate the mean ot the first column
np.mean(dataset[:, 0])

99.76743510416668

In [6]:
# Calculate the mean for every single row, aggregated in a list
np.mean(dataset, axis=1)

array([100.17764752,  97.27899259, 100.20466135, 100.56785907,
       100.98341406,  97.83018578, 101.49052285,  99.75332252,
       101.89845125,  99.77973914, 101.013081  , 100.54961696,
        98.48256886,  98.49816126, 101.85956927,  97.05201872,
       102.62147483, 101.21177037,  99.58777968,  98.96533534,
       103.85792812, 101.89050288,  99.07192574,  99.34233101])

In [7]:
# calculate the mean for every single columns
np.mean(dataset, axis=0)

array([ 99.7674351 ,  99.61229127, 101.14584656, 101.8449316 ,
        99.04871791,  99.67838931,  99.7848489 , 100.44049274])

In [8]:
# calculate the mean of the whole matrix
np.mean(dataset)

100.16536917390624

# Indexing, Slicing, Splitting, and Iterating

In [9]:
# Use simple indexing for the second row
np.mean(dataset[1])

97.27899259

In [10]:
# reverse index the last row and calculate the mean of that row
np.mean(dataset[-1])

99.34233100624999

In [11]:
# index the first value of the first row
np.mean(dataset[0][0])

99.14931546

In [12]:
# Use reverse indexing to access the last value of the second last row
np.mean(dataset[-2, -1])

103.83852459

In [13]:
# Create a 2x2 matrix that starts at the second row and second column
sub_matrix = dataset[1:3, 1:3]
np.mean(sub_matrix)

95.63393608250001

In [14]:
# have every other element of the fifth row
np.mean(dataset[4, ::2])

98.915396795

In [15]:
# split our dataset into two equal parts
h_split = np.hsplit(dataset, (2))

In [16]:
# Split the first third into two equal parts vertically
v_split = np.vsplit(dataset, (2))

In [17]:
# Iterate over the whole dataset
cont = 0
for x in np.nditer(dataset):
    print(x, cont)
    cont = cont + 1

99.14931546 0
104.03852715 1
107.43534677 2
97.85230675 3
98.74986914 4
98.80833412 5
96.81964892 6
98.56783189 7
92.02628776 8
97.10439252 9
99.32066924 10
97.24584816 11
92.9267508 12
92.65657752 13
105.7197853 14
101.23162942 15
95.66253664 16
95.17750125 17
90.93318132 18
110.18889465 19
98.80084371 20
105.95297652 21
98.37481387 22
106.54654286 23
91.37294597 24
100.96781394 25
100.40118279 26
113.42090475 27
105.48508838 28
91.6604946 29
106.1472841 30
95.08715803 31
101.20862522 32
103.5730309 33
100.28690912 34
105.85269352 35
93.37126331 36
108.57980357 37
100.79478953 38
94.20019732 39
102.80387079 40
98.29687616 41
93.24376389 42
97.24130034 43
89.03452725 44
96.2832753 45
104.60344836 46
101.13442416 47
106.71751618 48
102.97585605 49
98.45723272 50
100.72418901 51
106.39798503 52
95.46493436 53
94.35373179 54
106.83273763 55
96.02548256 56
102.82360856 57
106.47551845 58
101.34745901 59
102.45651798 60
98.74767493 61
97.57544275 62
92.5748759 63
105.30350449 64
92.87730812

In [18]:
# Use the ndenumerate method to iterate over the whole dataset
for index, value in np.ndenumerate(dataset):
    print(index, value)

(0, 0) 99.14931546
(0, 1) 104.03852715
(0, 2) 107.43534677
(0, 3) 97.85230675
(0, 4) 98.74986914
(0, 5) 98.80833412
(0, 6) 96.81964892
(0, 7) 98.56783189
(1, 0) 92.02628776
(1, 1) 97.10439252
(1, 2) 99.32066924
(1, 3) 97.24584816
(1, 4) 92.9267508
(1, 5) 92.65657752
(1, 6) 105.7197853
(1, 7) 101.23162942
(2, 0) 95.66253664
(2, 1) 95.17750125
(2, 2) 90.93318132
(2, 3) 110.18889465
(2, 4) 98.80084371
(2, 5) 105.95297652
(2, 6) 98.37481387
(2, 7) 106.54654286
(3, 0) 91.37294597
(3, 1) 100.96781394
(3, 2) 100.40118279
(3, 3) 113.42090475
(3, 4) 105.48508838
(3, 5) 91.6604946
(3, 6) 106.1472841
(3, 7) 95.08715803
(4, 0) 101.20862522
(4, 1) 103.5730309
(4, 2) 100.28690912
(4, 3) 105.85269352
(4, 4) 93.37126331
(4, 5) 108.57980357
(4, 6) 100.79478953
(4, 7) 94.20019732
(5, 0) 102.80387079
(5, 1) 98.29687616
(5, 2) 93.24376389
(5, 3) 97.24130034
(5, 4) 89.03452725
(5, 5) 96.2832753
(5, 6) 104.60344836
(5, 7) 101.13442416
(6, 0) 106.71751618
(6, 1) 102.97585605
(6, 2) 98.45723272
(6, 3) 100.724

# Filtering, Sorting, Combining, and Reshaping

In [19]:
# Get values greater than 105
vals_greater_five = dataset[dataset > 105]
vals_greater_five

array([107.43534677, 105.7197853 , 110.18889465, 105.95297652,
       106.54654286, 113.42090475, 105.48508838, 106.1472841 ,
       105.85269352, 108.57980357, 106.71751618, 106.39798503,
       106.83273763, 106.47551845, 105.30350449, 106.03868807,
       110.44484313, 106.6471081 , 105.0320535 , 107.02874163,
       105.07475277, 107.22482426, 107.19119932, 108.09423367,
       109.40523174, 106.11454989, 106.57052697, 105.13668343,
       105.37011896, 105.86078488, 106.89005002, 106.57364584,
       107.40064604, 106.38276709, 106.46476468, 110.43976681,
       105.02389857, 106.05042487])

In [20]:
# Extract the values of our dataset that are between the values 90 and 95
vals_between_90_95 = dataset[(dataset > 90) & ( dataset < 95)]
vals_between_90_95

array([92.02628776, 92.9267508 , 92.65657752, 90.93318132, 91.37294597,
       91.6604946 , 93.37126331, 94.20019732, 93.24376389, 94.35373179,
       92.5748759 , 92.87730812, 93.87155456, 92.75048583, 91.32093303,
       92.0108226 , 93.18884302, 93.83969256, 94.5081787 , 94.59300658,
       93.04610867, 91.6779221 , 94.76253572, 94.57421727, 94.11176915,
       93.97853495])

In [21]:
# Get the indices of values that have a delta of less than 1
rows, cols = np.where(abs(dataset - 100) < 1)

one_away_indices = [[rows[index], cols[index]] for (index, _) in np.ndenumerate(rows)]
one_away_indices

[[0, 0],
 [1, 2],
 [3, 1],
 [3, 2],
 [4, 2],
 [4, 6],
 [6, 3],
 [8, 5],
 [10, 1],
 [10, 3],
 [10, 5],
 [13, 0],
 [13, 4],
 [13, 7],
 [14, 3],
 [14, 5],
 [16, 1],
 [16, 6],
 [17, 2],
 [17, 3],
 [18, 7],
 [20, 4],
 [21, 0],
 [21, 4],
 [21, 5],
 [22, 2],
 [23, 1],
 [23, 7]]

In [22]:
# sort each row in our dataset
row_sorted = np.sort(dataset)
row_sorted

array([[ 96.81964892,  97.85230675,  98.56783189,  98.74986914,
         98.80833412,  99.14931546, 104.03852715, 107.43534677],
       [ 92.02628776,  92.65657752,  92.9267508 ,  97.10439252,
         97.24584816,  99.32066924, 101.23162942, 105.7197853 ],
       [ 90.93318132,  95.17750125,  95.66253664,  98.37481387,
         98.80084371, 105.95297652, 106.54654286, 110.18889465],
       [ 91.37294597,  91.6604946 ,  95.08715803, 100.40118279,
        100.96781394, 105.48508838, 106.1472841 , 113.42090475],
       [ 93.37126331,  94.20019732, 100.28690912, 100.79478953,
        101.20862522, 103.5730309 , 105.85269352, 108.57980357],
       [ 89.03452725,  93.24376389,  96.2832753 ,  97.24130034,
         98.29687616, 101.13442416, 102.80387079, 104.60344836],
       [ 94.35373179,  95.46493436,  98.45723272, 100.72418901,
        102.97585605, 106.39798503, 106.71751618, 106.83273763],
       [ 92.5748759 ,  96.02548256,  97.57544275,  98.74767493,
        101.34745901, 102.4565179

In [23]:
# Use the 0 axes to sort the values by column
col_sorted = np.sort(dataset, axis=0)
col_sorted

array([[ 91.37294597,  88.80221141,  90.93318132,  93.18884302,
         85.98839623,  91.6604946 ,  91.32093303,  92.5748759 ],
       [ 92.02628776,  91.6779221 ,  93.24376389,  94.59300658,
         89.03452725,  92.65657752,  93.04610867,  94.20019732],
       [ 94.11176915,  92.0108226 ,  93.83969256,  96.74630281,
         92.75048583,  95.19184343,  94.35373179,  94.76253572],
       [ 95.65982034,  92.87730812,  94.5081787 ,  97.24130034,
         92.9267508 ,  95.46493436,  96.50342927,  95.08715803],
       [ 95.66253664,  93.87155456,  97.75887636,  97.24584816,
         93.37126331,  95.62359311,  96.81964892,  95.85284217],
       [ 96.02548256,  94.57421727,  98.45723272,  97.62787811,
         93.97853495,  96.2832753 ,  96.89244283,  97.59572169],
       [ 96.10020311,  95.17750125,  99.32066924,  97.65393524,
         95.93799169,  96.34622848,  96.96851209,  98.00253006],
       [ 96.76814836,  96.59385486,  99.57859892,  97.85230675,
         98.29243952,  96.5937781

In [24]:
# Create a sorted index list and use fancy indexing to get access to sorted elements easily
index_sorted = np.argsort(dataset[0])
dataset[0][index_sorted]

array([ 96.81964892,  97.85230675,  98.56783189,  98.74986914,
        98.80833412,  99.14931546, 104.03852715, 107.43534677])

In [25]:
# Use the combining features to add the second half of the first column back together
half = np.hsplit(dataset, (2))
halfed_first = np.vsplit(half[0], (2))
halfed_first[0]

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465],
       [ 91.37294597, 100.96781394, 100.40118279, 113.42090475],
       [101.20862522, 103.5730309 , 100.28690912, 105.85269352],
       [102.80387079,  98.29687616,  93.24376389,  97.24130034],
       [106.71751618, 102.97585605,  98.45723272, 100.72418901],
       [ 96.02548256, 102.82360856, 106.47551845, 101.34745901],
       [105.30350449,  92.87730812, 103.19258339, 104.40518318],
       [110.44484313,  93.87155456, 101.5363647 ,  97.65393524],
       [101.3514185 , 100.37372248, 106.6471081 , 100.61742813],
       [ 97.21315663, 107.02874163, 102.17642112,  96.74630281]])

In [26]:
# Use vstack to vertically combine the halfed_first datasets
first_col = np.vstack([halfed_first[0], halfed_first[1]])
first_col

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465],
       [ 91.37294597, 100.96781394, 100.40118279, 113.42090475],
       [101.20862522, 103.5730309 , 100.28690912, 105.85269352],
       [102.80387079,  98.29687616,  93.24376389,  97.24130034],
       [106.71751618, 102.97585605,  98.45723272, 100.72418901],
       [ 96.02548256, 102.82360856, 106.47551845, 101.34745901],
       [105.30350449,  92.87730812, 103.19258339, 104.40518318],
       [110.44484313,  93.87155456, 101.5363647 ,  97.65393524],
       [101.3514185 , 100.37372248, 106.6471081 , 100.61742813],
       [ 97.21315663, 107.02874163, 102.17642112,  96.74630281],
       [ 95.65982034, 107.22482426, 107.19119932, 102.93039474],
       [100.39303522,  92.0108226 ,  97.75887636,  93.18884302],
       [103.1521596 , 109.40523174,  93.83969256,  99.95827854],
       [106.11454989,  88

In [27]:
# Use the hstack method to combine our already combined first_col with the second
first_second_col = np.hstack([first_col, half[1]])
first_second_col

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465,
         98.80084371, 105.95297652,  98.37481387, 106.54654286],
       [ 91.37294597, 100.96781394, 100.40118279, 113.42090475,
        105.48508838,  91.6604946 , 106.1472841 ,  95.08715803],
       [101.20862522, 103.5730309 , 100.28690912, 105.85269352,
         93.37126331, 108.57980357, 100.79478953,  94.20019732],
       [102.80387079,  98.29687616,  93.24376389,  97.24130034,
         89.03452725,  96.2832753 , 104.60344836, 101.13442416],
       [106.71751618, 102.97585605,  98.45723272, 100.72418901,
        106.39798503,  95.46493436,  94.35373179, 106.83273763],
       [ 96.02548256, 102.82360856, 106.47551845, 101.34745901,
        102.45651798,  98.7476749

In [28]:
# Reshape our dataset
single_list = np.reshape(dataset, (1, -1))
single_list

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189,
         92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942,
         95.66253664,  95.17750125,  90.93318132, 110.18889465,
         98.80084371, 105.95297652,  98.37481387, 106.54654286,
         91.37294597, 100.96781394, 100.40118279, 113.42090475,
        105.48508838,  91.6604946 , 106.1472841 ,  95.08715803,
        101.20862522, 103.5730309 , 100.28690912, 105.85269352,
         93.37126331, 108.57980357, 100.79478953,  94.20019732,
        102.80387079,  98.29687616,  93.24376389,  97.24130034,
         89.03452725,  96.2832753 , 104.60344836, 101.13442416,
        106.71751618, 102.97585605,  98.45723272, 100.72418901,
        106.39798503,  95.46493436,  94.35373179, 106.83273763,
         96.02548256, 102.82360856, 106.47551845, 101.34745901,
        102.45651798,  98.74767493,  97.

# Loading a Sample Dataset and Calculating the Mean using Pandas

In [29]:
# import package
import pandas as pd

In [30]:
# load the data
dataset = pd.read_csv('Datasets/world_population.csv', index_col=0)
dataset.head()

Country Code                                     Indicator Name  \
Country Name                                                                   
Aruba                 ABW  Population density (people per sq. km of land ...   
Andorra               AND  Population density (people per sq. km of land ...   
Afghanistan           AFG  Population density (people per sq. km of land ...   
Angola                AGO  Population density (people per sq. km of land ...   
Albania               ALB  Population density (people per sq. km of land ...   

             Indicator Code  1960        1961        1962        1963  \
Country Name                                                            
Aruba           EN.POP.DNST   NaN  307.972222  312.366667  314.983333   
Andorra         EN.POP.DNST   NaN   30.587234   32.714894   34.914894   
Afghanistan     EN.POP.DNST   NaN   14.038148   14.312061   14.599692   
Angola          EN.POP.DNST   NaN    4.305195    4.384299    4.464433   
Albania         EN.POP.DNST   NaN   60.576642   62.456898   64.329234   

                    1964        1965        1966  ...        2007        2008  \
Country Name                                      ...                           
Aruba         316.827778  318.666667  320.622222  ...  562.322222  563.011111   
Andorra        37.170213   39.470213   41.800000  ...  180.591489  182.161702   
Afghanistan    14.901579   15.218206   15.545203  ...   39.637202   40.634655   
Angola          4.544558    4.624228    4.703271  ...   15.387749   15.915819   
Albania        66.209307   68.058066   69.874927  ...  108.394781  107.566204   

                    2009        2010        2011        2012        2013  \
Country Name                                                               
Aruba         563.422222  564.427778  566.311111  568.850000  571.783333   
Andorra       181.859574  179.614894  175.161702  168.757447  161.493617   
Afghanistan    41.674005   42.830327   44.127634   45.533197   46.997059   
Angola         16.459536   17.020898   17.600302   18.196544   18.808215   
Albania       106.843759  106.314635  106.013869  105.848431  105.717226   

                    2014        2015  2016  
Country Name                                
Aruba         574.672222  577.161111   NaN  
Andorra       154.863830  149.942553   NaN  
Afghanistan    48.444546   49.821649   NaN  
Angola         19.433323   20.070565   NaN  
Albania       105.607810  105.444051   NaN  

[5 rows x 60 columns]

In [31]:
# print the shape
dataset.shape

(264, 60)

In [32]:
# Index the column with the year 1961 and calculate the mean
dataset['1961'].mean()

176.91514132840538

In [33]:
# index the column with the year 2015 and calculate the mean
dataset['2015'].mean()

368.7066010400187

In [34]:
# get the mean for every single country
dataset.mean(axis=1)

Country Name
Aruba               413.944949
Andorra             106.838839
Afghanistan          25.373379
Angola                9.649583
Albania              99.159197
                       ...    
Yemen, Rep.          24.702231
South Africa         28.599504
Congo, Dem. Rep.     16.661282
Zambia               11.055234
Zimbabwe             24.520532
Length: 264, dtype: float64

In [35]:
# get the mean for each column
dataset.mean(axis=0).tail()

2012    357.787305
2013    360.985726
2014    364.849194
2015    368.706601
2016           NaN
dtype: float64

In [36]:
# Calculate the mean of the whole DataFrame
dataset.mean()

1960           NaN
1961    176.915141
1962    180.703231
1963    184.572413
1964    188.461797
1965    192.412363
1966    196.145042
1967    200.118063
1968    203.879464
1969    207.336102
1970    210.607871
1971    213.489694
1972    215.998475
1973    218.438708
1974    220.621210
1975    223.046375
1976    224.960258
1977    227.006734
1978    229.187306
1979    232.510772
1980    236.185357
1981    240.789508
1982    246.175178
1983    251.342389
1984    256.647822
1985    261.680751
1986    266.647038
1987    271.768300
1988    276.813259
1989    281.850054
1990    286.062387
1991    288.292566
1992    293.305416
1993    297.759160
1994    302.275463
1995    304.537276
1996    309.714948
1997    313.896935
1998    320.405981
1999    324.004669
2000    327.270760
2001    312.259570
2002    313.269043
2003    315.847613
2004    317.746559
2005    322.669534
2006    326.907971
2007    331.995474
2008    338.688417
2009    343.649206
2010    347.967029
2011    351.942027
2012    357.

# Using pandas to Compute the Mean, Median, and Variance of a Dataset

In [37]:
# Calculate the mean value of the values labeled as Germany
dataset.loc[['Germany']].mean(axis=1)

Country Name
Germany    227.773688
dtype: float64

In [38]:
# Calculate the median value of the last row
dataset.iloc[[-1]].median(axis=1)

Country Name
Zimbabwe    25.505431
dtype: float64

In [39]:
# Calculate the median population density values for the first 10 countries
dataset.iloc[0:10, :].median(axis=1)

Country Name
Aruba                   348.022222
Andorra                 107.300000
Afghanistan              19.998926
Angola                    8.458253
Albania                 106.001058
Arab World               15.307283
United Arab Emirates     19.305072
Argentina                11.618238
Armenia                 105.898033
American Samoa          220.245000
dtype: float64

In [40]:
# Calculate the variance of the dataset and return only the last five columns
dataset.var().tail()

2012    3.063475e+06
2013    3.094597e+06
2014    3.157111e+06
2015    3.220634e+06
2016             NaN
dtype: float64

In [41]:
# Calculate the mean for the year 2015 using both NumPy and pandas
print('mean with pandas:', dataset['2015'].mean())
print('mean with numpy:', np.mean(dataset['2015']))

mean with pandas: 368.7066010400187
mean with numpy: 368.7066010400187


# Indexing, Slicing, and Iterating Using pandas

In [42]:
# Index the row with the index_col "United States"
dataset.loc[['United States']].head()

Country Code                                     Indicator Name  \
Country Name                                                                    
United States          USA  Population density (people per sq. km of land ...   

              Indicator Code  1960      1961       1962       1963       1964  \
Country Name                                                                    
United States    EN.POP.DNST   NaN  20.05588  20.366723  20.661953  20.950959   

                    1965       1966  ...       2007       2008       2009  \
Country Name                         ...                                    
United States  21.214527  21.460952  ...  32.878611  33.243687  33.536399   

                    2010       2011       2012       2013       2014  \
Country Name                                                           
United States  33.817936  34.077243  34.337838  34.591983  34.863098   

                    2015  2016  
Country Name                    
United States  35.137648   NaN  

[1 rows x 60 columns]

In [43]:
# index the second to last row
dataset.iloc[[-2]]

Country Code                                     Indicator Name  \
Country Name                                                                   
Zambia                ZMB  Population density (people per sq. km of land ...   

             Indicator Code  1960      1961      1962      1963      1964  \
Country Name                                                                
Zambia          EN.POP.DNST   NaN  4.227724  4.359305  4.496824  4.639914   

                  1965      1966  ...       2007       2008       2009  \
Country Name                      ...                                    
Zambia        4.788452  4.942343  ...  17.135926  17.641587  18.170609   

                   2010       2011       2012       2013       2014      2015  \
Country Name                                                                    
Zambia        18.721585  19.294752  19.890745  20.508866  21.148177  21.80789   

              2016  
Country Name        
Zambia         NaN  

[1 rows x 60 columns]

In [44]:
# Index the column with the header of 2000
dataset['2000'].head()

Country Name
Aruba          504.766667
Andorra        139.146809
Afghanistan     30.177894
Angola          12.078798
Albania        112.738212
Name: 2000, dtype: float64

In [45]:
# get the data for the year 2000 as a DataFrame and then select India
dataset[['2000']].loc[['India']]

2000
Country Name            
India         354.326858

In [46]:
# Use the single brackets notation to get the distinct value for the population density of India in 2000
dataset['2000']['India']

354.326858357522

In [47]:
# Create a slice with the rows 2 to 5
dataset[1:5]

Country Code                                     Indicator Name  \
Country Name                                                                   
Andorra               AND  Population density (people per sq. km of land ...   
Afghanistan           AFG  Population density (people per sq. km of land ...   
Angola                AGO  Population density (people per sq. km of land ...   
Albania               ALB  Population density (people per sq. km of land ...   

             Indicator Code  1960       1961       1962       1963       1964  \
Country Name                                                                    
Andorra         EN.POP.DNST   NaN  30.587234  32.714894  34.914894  37.170213   
Afghanistan     EN.POP.DNST   NaN  14.038148  14.312061  14.599692  14.901579   
Angola          EN.POP.DNST   NaN   4.305195   4.384299   4.464433   4.544558   
Albania         EN.POP.DNST   NaN  60.576642  62.456898  64.329234  66.209307   

                   1965       1966  ...        2007        2008        2009  \
Country Name                        ...                                       
Andorra       39.470213  41.800000  ...  180.591489  182.161702  181.859574   
Afghanistan   15.218206  15.545203  ...   39.637202   40.634655   41.674005   
Angola         4.624228   4.703271  ...   15.387749   15.915819   16.459536   
Albania       68.058066  69.874927  ...  108.394781  107.566204  106.843759   

                    2010        2011        2012        2013        2014  \
Country Name                                                               
Andorra       179.614894  175.161702  168.757447  161.493617  154.863830   
Afghanistan    42.830327   44.127634   45.533197   46.997059   48.444546   
Angola         17.020898   17.600302   18.196544   18.808215   19.433323   
Albania       106.314635  106.013869  105.848431  105.717226  105.607810   

                    2015  2016  
Country Name                    
Andorra       149.942553   NaN  
Afghanistan    49.821649   NaN  
Angola         20.070565   NaN  
Albania       105.444051   NaN  

[4 rows x 60 columns]

In [48]:
# Slice the dataset to get the rows for Germany, Singapore, United States, and India
dataset.loc[['Germany', 'Singapore', 'United States', 'India']]

Country Code                                     Indicator Name  \
Country Name                                                                    
Germany                DEU  Population density (people per sq. km of land ...   
Singapore              SGP  Population density (people per sq. km of land ...   
United States          USA  Population density (people per sq. km of land ...   
India                  IND  Population density (people per sq. km of land ...   

              Indicator Code  1960         1961         1962         1963  \
Country Name                                                                
Germany          EN.POP.DNST   NaN   210.172807   212.029284   214.001527   
Singapore        EN.POP.DNST   NaN  2540.895522  2612.238806  2679.104478   
United States    EN.POP.DNST   NaN    20.055880    20.366723    20.661953   
India            EN.POP.DNST   NaN   154.275864   157.424902   160.679256   

                      1964         1965         1966  ...         2007  \
Country Name                                          ...                
Germany         215.731495   217.579970   219.403406  ...   235.943362   
Singapore      2748.656716  2816.268657  2887.164179  ...  6602.300719   
United States    20.950959    21.214527    21.460952  ...    32.878611   
India           164.029246   167.470047   170.995768  ...   396.774384   

                      2008         2009         2010         2011  \
Country Name                                                        
Germany         235.522178   234.939637   234.606908   234.673150   
Singapore      6913.422857  7125.104286  7231.811966  7363.193182   
United States    33.243687    33.536399    33.817936    34.077243   
India           402.621463   408.376922   414.028200   419.564848   

                      2012         2013         2014         2015  2016  
Country Name                                                             
Germany         230.750625   235.647997   232.347794   233.583362   NaN  
Singapore      7524.698300  7636.721358  7736.526167  7828.857143   NaN  
United States    34.337838    34.591983    34.863098    35.137648   NaN  
India           424.994581   430.345479   435.657171   440.957533   NaN  

[4 rows x 60 columns]

In [49]:
# Use chaining to get the rows for Germany, Singapore, United States, and India 
# and return only the values for the years 1970, 1990, and 2010
dataset.loc[['Germany', 'Singapore', 'United States', 'India']][['1970', '1990', '2010']]

1970         1990         2010
Country Name                                        
Germany         223.897371   227.517054   234.606908
Singapore      3096.268657  4547.958209  7231.811966
United States    22.388131    27.254514    33.817936
India           186.312757   292.817404   414.028200

In [50]:
# Iterate our dataset and print out the countries up until Angola
for index, row in dataset.iterrows():
    if index == 'Angola':
        break
    print(index, '\n', row[['Country Code', '1970', '1990', '2010']], '\n')

Aruba 
 Country Code        ABW
1970            328.139
1990            345.267
2010            564.428
Name: Aruba, dtype: object 

Andorra 
 Country Code        AND
1970            51.6574
1990            115.981
2010            179.615
Name: Andorra, dtype: object 

Afghanistan 
 Country Code        AFG
1970            17.0344
1990            18.4842
2010            42.8303
Name: Afghanistan, dtype: object 



# Filtering, Sorting, and Reshaping

In [51]:
# Filter the dataset for columns 1961, 2000, and 2015
dataset.filter(items=['1961', '2000', '2015']).head()

1961        2000        2015
Country Name                                    
Aruba         307.972222  504.766667  577.161111
Andorra        30.587234  139.146809  149.942553
Afghanistan    14.038148   30.177894   49.821649
Angola          4.305195   12.078798   20.070565
Albania        60.576642  112.738212  105.444051

In [52]:
# Use conditions to get all the countries that had a higher population density than 500 in 2000
dataset[dataset['2000'] > 500][['2000']]

2000
Country Name                           
Aruba                        504.766667
Bangladesh                  1008.532988
Bahrain                      939.232394
Bermuda                     1236.660000
Barbados                     627.530233
Channel Islands              766.623711
Gibraltar                   2735.100000
Hong Kong SAR, China        6347.619048
Macao SAR, China           21595.350000
St. Martin (French part)     521.764706
Monaco                     16040.500000
Maldives                     953.333333
Malta                       1191.759375
Mauritius                    584.666502
Nauru                        502.100000
Singapore                   6011.771642
Sint Maarten (Dutch part)    897.617647

In [53]:
# Get all the columns that start with 2 
dataset.filter(regex='^2').head()

2000        2001        2002        2003        2004  \
Country Name                                                               
Aruba         504.766667  516.077778  527.750000  538.972222  548.566667   
Andorra       139.146809  144.191489  151.161702  159.112766  166.674468   
Afghanistan    30.177894   31.448029   32.912231   34.475030   35.995236   
Angola         12.078798   12.483188   12.921871   13.388462   13.873025   
Albania       112.738212  111.685146  111.350730  110.934891  110.472226   

                    2005        2006        2007        2008        2009  \
Country Name                                                               
Aruba         555.727778  560.166667  562.322222  563.011111  563.422222   
Andorra       172.814894  177.389362  180.591489  182.161702  181.859574   
Afghanistan    37.373936   38.574296   39.637202   40.634655   41.674005   
Angola         14.368286   14.872437   15.387749   15.915819   16.459536   
Albania       109.908285  109.217044  108.394781  107.566204  106.843759   

                    2010        2011        2012        2013        2014  \
Country Name                                                               
Aruba         564.427778  566.311111  568.850000  571.783333  574.672222   
Andorra       179.614894  175.161702  168.757447  161.493617  154.863830   
Afghanistan    42.830327   44.127634   45.533197   46.997059   48.444546   
Angola         17.020898   17.600302   18.196544   18.808215   19.433323   
Albania       106.314635  106.013869  105.848431  105.717226  105.607810   

                    2015  2016  
Country Name                    
Aruba         577.161111   NaN  
Andorra       149.942553   NaN  
Afghanistan    49.821649   NaN  
Angola         20.070565   NaN  
Albania       105.444051   NaN

In [54]:
# Use the like query to find only the countries that contain the word land
dataset.filter(like='land', axis=0).head()

Country Code  \
Country Name                   
Switzerland              CHE   
Channel Islands          CHI   
Cayman Islands           CYM   
Finland                  FIN   
Faroe Islands            FRO   

                                                    Indicator Name  \
Country Name                                                         
Switzerland      Population density (people per sq. km of land ...   
Channel Islands  Population density (people per sq. km of land ...   
Cayman Islands   Population density (people per sq. km of land ...   
Finland          Population density (people per sq. km of land ...   
Faroe Islands    Population density (people per sq. km of land ...   

                Indicator Code  1960        1961        1962        1963  \
Country Name                                                               
Switzerland        EN.POP.DNST   NaN  137.479609  141.009285  144.056036   
Channel Islands    EN.POP.DNST   NaN  569.067010  574.551546  580.386598   
Cayman Islands     EN.POP.DNST   NaN   33.441667   33.925000   34.283333   
Finland            EN.POP.DNST   NaN   14.645934   14.745865   14.850484   
Faroe Islands      EN.POP.DNST   NaN   24.878223   25.181232   25.465616   

                       1964        1965        1966  ...        2007  \
Country Name                                         ...               
Switzerland      146.458915  148.160089  149.716707  ...  191.090115   
Channel Islands  586.484536  592.742268  599.103093  ...  806.783505   
Cayman Islands    34.579167   34.879167   35.175000  ...  214.500000   
Finland           14.933330   14.983197   15.039460  ...   17.391956   
Faroe Islands     25.749284   26.047994   26.363897  ...   34.813037   

                       2008        2009        2010        2011        2012  \
Country Name                                                                  
Switzerland      193.533632  195.966975  198.018752  200.232766  202.370204   
Channel Islands  812.304124  817.592784  839.910526  844.678947  849.136842   
Cayman Islands   220.520833  226.187500  231.287500  235.750000  239.675000   
Finland           17.484038   17.567855   17.648411   17.730995   17.815562   
Faroe Islands     34.834527   34.823066   34.790115   34.736390   34.665473   

                       2013        2014        2015  2016  
Country Name                                               
Switzerland      204.710649  207.223631  209.711914   NaN  
Channel Islands  853.357895  857.457895  861.536842   NaN  
Cayman Islands   243.204167  246.550000  249.862500   NaN  
Finland           17.897831   17.972003   18.039465   NaN  
Faroe Islands     34.593123   34.542264   34.526504   NaN  

[5 rows x 60 columns]

In [55]:
# Use the sort_values method to get the countries with the lowest population density for the year 1961
dataset.sort_values(by=['1961'])[['1961']].head()

1961
Country Name          
Greenland     0.098625
Mongolia      0.632212
Namibia       0.749775
Libya         0.843320
Mauritania    0.856916

In [56]:
# Sort column 2015 in descending order
dataset.sort_values(by=['2015'], ascending=False)[['2015']].head()

2015
Country Name                      
Macao SAR, China      19392.937294
Monaco                18865.500000
Singapore              7828.857143
Hong Kong SAR, China   6957.809524
Gibraltar              3221.700000

In [57]:
# Get a DataFrame where the columns are country codes and the only row is the year 2015
dataset_2015 = dataset[['Country Code', '2015']]
dataset_2015.pivot(index=['2015'] * len(dataset_2015), columns='Country Code', values='2015')

Country Code         ABW        AFG        AGO         ALB         AND  \
2015          577.161111  49.821649  20.070565  105.444051  149.942553   

Country Code        ARB        ARE        ARG         ARM     ASM  ...  \
2015          28.779858  109.53305  15.864696  105.996207  277.69  ...   

Country Code     VGB         VIR         VNM        VUT        WLD        WSM  \
2015          200.78  295.925714  295.751927  21.710582  56.627369  68.278445   

Country Code        YEM        ZAF       ZMB        ZWE  
2015          50.821477  45.303251  21.80789  40.332819  

[1 rows x 264 columns]